import {label,ui,displayStatus} from './i18n.js';
const esc = v => String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export async function openOCR(ctx,fileId) {
  const data=await ctx.request(ctx.projectPath(`/files/${encodeURIComponent(fileId)}/ocr`));
  const caps=await ctx.request('/ocr');
  const editable=['engineer','reviewer'].includes(ctx.role),reviewer=ctx.role==='reviewer';
  ctx.openModal('Scanned page review',`<p>${label('OCR text is unverified until a reviewer checks the page image, every number, unit and table column.')}</p><p>${label('Optional local OCR')}: ${esc(caps.provider||ui('Unavailable'))} · ${label(caps.enabled?'Enabled':'Disabled')}</p>${editable?`<form method="post" id="ocr-extract-form" class="form-stack"><label>${label('PDF page')}<input name="page" type="number" min="1" max="200" required value="1"></label><button type="submit" class="button">${label('Recognize selected page')}</button></form>`:''}<div>${data.items.map(r=>`<article class="list-card"><h3>${label('PDF page')} ${r.page} · <span data-i18n-status="${esc(r.state)}">${esc(displayStatus(r.state))}</span></h3><img class="ocr-image" data-ocr-image="${esc(r.image_file_id)}" alt="${esc(ui('Original page image'))}" data-i18n-alt="Original page image"><details class="raw-details"><summary>${label('Recognition text and line positions')}</summary><pre class="code-block">${esc(JSON.stringify(r.lines,null,2))}</pre></details>${r.state==='PENDING_REVIEW'&&reviewer?`<form method="post" class="ocr-confirm-form form-stack" data-ocr="${esc(r.id)}"><label>${label('Corrected transcription')}<textarea name="text" rows="8" required maxlength="200000">${esc(r.text)}</textarea></label><label>${label('Review reason')}<textarea name="reason" rows="2" required maxlength="1000"></textarea></label><label class="checkbox-label"><input name="confirmed" type="checkbox" required>${label('I checked decimals, minus signs, units and table column relationships against the image.')}</label><button type="submit" class="button primary">${label('Confirm page transcription')}</button></form>`:`<pre class="code-block">${esc(r.confirmed_text||r.text)}</pre><p>${label('Confirmed by')}: ${esc(r.confirmed_by||'—')}</p>`}</article>`).join('')}</div>`, `<button class="button" data-action="close-modal">${label('Close')}</button>`);
  for(const image of document.querySelectorAll('[data-ocr-image]')){
    const response=await ctx.request(ctx.projectPath(`/files/${encodeURIComponent(image.dataset.ocrImage)}/content`),{raw:true});
    const blob=new Blob([await response.arrayBuffer()],{type:'image/png'}),url=URL.createObjectURL(blob);image.src=url;setTimeout(()=>URL.revokeObjectURL(url),300000);
  }
  const extract=document.getElementById('ocr-extract-form');
  extract?.addEventListener('submit',async e=>{e.preventDefault();const b=extract.querySelector('button');b.disabled=true;try{await ctx.request(ctx.projectPath(`/files/${encodeURIComponent(fileId)}/ocr`),{method:'POST',body:{page:Number(extract.page.value)}});await openOCR(ctx,fileId);}catch(error){ctx.error(error);}finally{b.disabled=false;}});
  for(const form of document.querySelectorAll('.ocr-confirm-form'))form.addEventListener('submit',async e=>{e.preventDefault();const b=form.querySelector('button');b.disabled=true;try{await ctx.request(ctx.projectPath(`/ocr/${encodeURIComponent(form.dataset.ocr)}/confirm`),{method:'POST',body:{text:form.text.value,reason:form.reason.value,numbers_units_columns_checked:form.confirmed.checked}});await ctx.refresh();await openOCR(ctx,fileId);}catch(error){ctx.error(error);}finally{b.disabled=false;}});
}
